<?php
/**
 * Created by PhpStorm.
 * User: Bogdan
 * Date: 02.08.2017
 * Time: 10:55
 */

namespace app\widgets;


use Yii;

class ExportMenu extends \kartik\export\ExportMenu
{
    public $customColumns = [];
    public $showConfirmAlert = false;
    public $target = self::TARGET_SELF;
    public $initProvider = true;
    protected function setDefaultExportConfig(){
        $isFa = $this->fontAwesome;
        $this->_defaultExportConfig = [
            self::FORMAT_CSV => [
                'label' => Yii::t('kvexport', 'CSV'),
                'icon' => $isFa ? 'file-code-o' : 'floppy-open',
                'iconOptions' => ['class' => 'text-primary'],
                'linkOptions' => [],
                'options' => ['title' => Yii::t('kvexport', 'Comma Separated Values')],
                'alertMsg' => Yii::t('kvexport', 'The CSV export file will be generated for download.'),
                'mime' => 'application/csv',
                'extension' => 'csv',
                'writer' => 'CSV',
            ],
            self::FORMAT_EXCEL => [
                'label' => Yii::t('kvexport', 'Excel 95 +'),
                'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
                'iconOptions' => ['class' => 'text-success'],
                'linkOptions' => [],
                'options' => ['title' => Yii::t('kvexport', 'Microsoft Excel 95+ (xls)')],
                'alertMsg' => Yii::t('kvexport', 'The EXCEL 95+ (xls) export file will be generated for download.'),
                'mime' => 'application/vnd.ms-excel',
                'extension' => 'xls',
                'writer' => 'Excel5',
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}