<?php

namespace app\models;

use app\components\keyStorage\KeyStorage;
use app\interfaces\RuleInterface;
use yii\base\Model;

/**
 * Class RulesSettings
 * @package app\models
 * @property KeyStorage $keyStorage
 * @property $pointCounts number
 * @property $ruleName string
 * @property Page $page
 */

class RulesSettingsForm extends  Model{
    public $pointCounts;
    public $description;
    public $visitCount;

    public $ruleName;
    protected $keyStorage;
    public $group;

    protected function getFormat($name  = 'points'){
        return sprintf("%s\%d\%d\%s", $this->ruleName, \Yii::$app->getUser()->identity->getId(), $this->group->id, $name);
    }

    public function __construct(array $config = [])
    {
        $this->keyStorage = \Yii::$app->keyStorage;

        parent::__construct($config);

        if($this->keyStorage->get($this->getFormat('points'))){
            $this->pointCounts = $this->keyStorage->get($this->getFormat());
        }else{
            //Default valve
            $this->pointCounts = 0;
        }

        if($this->keyStorage->get($this->getFormat('vcount'))){
            $this->visitCount = $this->keyStorage->get($this->getFormat('vcount'));
        }else{
            //Default valve
            $this->visitCount = 0;
        }
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            [['pointCounts', 'description', 'visitCount'], 'required'],
            [['pointCounts', 'visitCount'], 'number', 'min' => 1],
            [['description'], 'string', 'max' => 255]
        ]); // TODO: Change the autogenerated stub
    }

    public function setRule($ruleName){
        /**
         * @var $rule RuleInterface
         */
        $rule = new $ruleName;
        $this->description = $rule->getDescription();
        $this->ruleName = $ruleName;
    }

    public function save(){
        $this->keyStorage->set($this->getFormat('points'), $this->pointCounts);
        $this->keyStorage->set($this->getFormat('vcount'), $this->visitCount);
    }
}